onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

minimumReleaseAgeExclude:
  - '@qualcomm-ui/*'
  - '@angular/build@22.1.5'
  - '@angular/common@22.1.3'
  - '@angular/compiler-cli@22.1.3'
  - '@angular/compiler@22.1.3'
  - '@angular/core@22.1.3'
  - '@angular/forms@22.1.3'
  - '@angular/platform-browser@22.1.3'
  - '@angular/platform-server@22.1.3'
  - '@angular/router@22.1.3'
  - '@schematics/angular@22.1.5'

minimumReleaseAge: 1440

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  unrs-resolver: true
