import type { Metadata } from "next";
import {
  Roboto_Flex,
  Roboto_Mono,
} from "next/font/google"
import "./globals.css";
import {
  type ReactNode,
} from "react"
import {ThemeProvider} from "next-themes"
import {QuiRoot} from "@qualcomm-ui/react/qui-root"

const sansFont = Roboto_Flex({
  variable: "--font-roboto-flex",
  weight: ["400", "500", "600"],
  subsets: ["latin"],
});

const monoFont = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning data-brand="qualcomm">
      <body
        className={`${sansFont.variable} ${monoFont.variable} antialiased`}
      >
        <ThemeProvider
          value={{dark: "dark", light: "light", system: "test"}}
          themes={["dark", "light"]}
          attribute="data-theme"
          defaultTheme="light"
          enableSystem={false}
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
