FROM public.ecr.aws/docker/library/node:lts-slim

WORKDIR /app

COPY . .

ENV COREPACK_ENABLE_DOWNLOAD_PROMPT=0

RUN apt update && apt install -y git && rm -rf /var/lib/apt/lists/*

# install and build
RUN corepack enable
RUN pnpm install --frozen-lockfile
RUN pnpm build
ENV NODE_ENV=production

EXPOSE 3000

CMD ["pnpm", "start"]
